#!/bin/bash -x
#SBATCH --account=pra116
#SBATCH --nodes=22
#SBATCH --ntasks-per-node=8
#SBATCH -J JOBNAME                                                                                                                            
#SBATCH --exclusive

# if keyword omitted: Max. 96 tasks per node
#SBATCH --cpus-per-task=12

# for OpenMP/hybrid jobs only
#SBATCH --output=std_out.txt
#SBATCH --error=std_error.txt
#SBATCH --time=24:00:00
#SBATCH --partition=batch

# "batch" for normal use or "devel" for up to 8 nodes up to 2 hours

# *** start of job script ***
# Note: The current working directory at this point is
# the directory where sbatch was executed.
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
srun /p/home/jusers/bamber1/juwels/GRChombo/Examples/BinaryBHScalarField/Main_BinaryBH3d.Linux.64.mpiicpc.ifort.OPTHIGH.MPI.OPENMPCC.PETSC.ex ../params.txt


