#!/bin/bash
# Job Name and Files (also --job-name)
#SBATCH -J N16_KC_test

#Output and error (also --output, --error):
#SBATCH -o ./%x.%j.out
#SBATCH -e ./%x.%j.err

#Initial working directory (also --chdir):
#SBATCH -D ./

#Notification and type
#SBATCH --mail-type=ALL
#SBATCH --mail-user=katy.a.clough@gmail.com

# Wall clock limit:
#SBATCH --time=0:30:00
#SBATCH --no-requeue

#Setup of execution environment
#SBATCH --export=NONE
#SBATCH --get-user-env
#SBATCH --account=pn34tu
#SBATCH --partition=test

#Number of nodes and MPI tasks per node:
#SBATCH --nodes=16
# There are 48 physical cores per node, so
# the product of these numbers should be 48
#SBATCH --ntasks-per-node=16
export OMP_NUM_THREADS=3

#Load modules
module load slurm_setup
module load intel mkl hdf5 gcc/7
 
#Default Pinning:
#Thread0/Task0 ->CPU0 or CPU48
#Thread1/Task0 ->CPU1 or CPU49
#Thread2/Task0 ->CPU2 or CPU50

#Run the program:
mpiexec -n $SLURM_NTASKS ./Main_ProcaField3d.Linux.64.mpiicpc.ifort.OPTHIGH.MPI.ex params.txt

